export  const productsData = [
    {
    id: 1,
    name: "Brownie Clásico",
    category: "Brownies",
    price: 120.00,
    rating: 4.9,
    numReviews: 85,
    description: "Brownie de chocolate intenso con nueces pecan y una textura húmeda perfecta.",
    ingredients: ["Chocolate amargo", "Nueces pecan", "Harina", "Azúcar", "Huevos", "Manteca"],
    allergens: ["Gluten", "Huevos", "Frutos secos"],
    calories: "380 kcal por porción",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4DdcHpKlj3GHaQ1uIn8nTOxP0ObNB9d0lHQ&s",
    tags: ["chocolate", "intenso"],
    images: [
      "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
      "https://chewinghappiness.com/wp-content/uploads/2020/03/Brownie-de-Maca-1080x675.jpg"
    ],
    colors: ["#4B2E2B"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 2,
    name: "Alfajor de Maicena",
    category: "Alfajores",
    price: 90.00,
    rating: 4.7,
    numReviews: 102,
    description: "Tradicional alfajor relleno de dulce de leche y bordes con coco rallado.",
    ingredients: ["Maicena", "Dulce de leche", "Manteca", "Azúcar impalpable", "Huevos"],
    allergens: ["Lácteos", "Gluten", "Huevos"],
    calories: "290 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["clásico", "suave"],
    images: [
      "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
      "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png"
    ],
    colors: ["#F5E4C3"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 3,
    name: "Galletas de Avena y Pasas",
    category: "Galletas",
    price: 60.00,
    rating: 4.3,
    numReviews: 60,
    description: "Crujientes por fuera, suaves por dentro, con avena integral y pasas dulces.",
    ingredients: ["Avena", "Pasas", "Harina integral", "Manteca", "Canela"],
    allergens: ["Gluten"],
    calories: "250 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["integral", "casero"],
    images: [],
    colors: ["#D2A679"],
    isNew: true,
    isBestseller: false
  },
  {
    id: 4,
    name: "Tarta de Limón y Merengue",
    category: "Tartas",
    price: 230.00,
    rating: 4.8,
    numReviews: 95,
    description: "Base crocante con crema de limón natural y un suave merengue italiano.",
    ingredients: ["Limón", "Azúcar", "Huevos", "Harina", "Manteca"],
    allergens: ["Huevos", "Gluten"],
    calories: "340 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["ácido", "refrescante"],
    images: [],
    colors: ["#FFFACD"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 5,
    name: "Torta de Zanahoria",
    category: "Tortas",
    price: 280.00,
    rating: 4.9,
    numReviews: 110,
    description: "Bizcochuelo húmedo de zanahoria con frosting de queso crema y nueces.",
    ingredients: ["Zanahoria", "Nueces", "Harina", "Azúcar", "Queso crema"],
    allergens: ["Gluten", "Frutos secos", "Lácteos"],
    calories: "410 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["especiado", "suave"],
    images: [],
    colors: ["#F4A460"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 6,
    name: "Empanada de Manzana",
    category: "Empanadas",
    price: 75.00,
    rating: 4.6,
    numReviews: 78,
    description: "Empanada de hojaldre rellena con manzanas caramelizadas y un toque de canela.",
    ingredients: ["Manzana", "Azúcar", "Canela", "Masa de hojaldre"],
    allergens: ["Gluten"],
    calories: "320 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["dulce", "horneado"],
    images: [],
    colors: ["#FFD700"],
    isNew: true,
    isBestseller: false
  },
  {
    id: 7,
    name: "Bites de Cheesecake",
    category: "Bites",
    price: 150.00,
    rating: 4.8,
    numReviews: 90,
    description: "Mini porciones de cheesecake con base de galleta y topping de frutos rojos.",
    ingredients: ["Queso crema", "Galletas", "Frutos rojos", "Azúcar"],
    allergens: ["Lácteos", "Gluten"],
    calories: "220 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["mini", "fresco"],
    images: [],
    colors: ["#FFB6C1"],
    isNew: true,
    isBestseller: true
  },
  {
    id: 8,
    name: "Coctail de Frutas en Gelatina",
    category: "Coctail",
    price: 95.00,
    rating: 4.2,
    numReviews: 55,
    description: "Cubos de frutas tropicales en gelatina natural, ideal para eventos.",
    ingredients: ["Frutas tropicales", "Gelatina sin sabor", "Jugo natural"],
    allergens: [],
    calories: "150 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["ligero", "colorido"],
    images: [],
    colors: ["#FF69B4"],
    isNew: true,
    isBestseller: false
  },

  // Repetimos con nuevas variantes:
  {
    id: 9,
    name: "Brownie con Dulce de Leche",
    category: "Brownies",
    price: 135.00,
    rating: 4.9,
    numReviews: 67,
    description: "Brownie clásico con corazón de dulce de leche argentino.",
    ingredients: ["Chocolate", "Dulce de leche", "Harina", "Azúcar", "Huevos"],
    allergens: ["Gluten", "Huevos", "Lácteos"],
    calories: "390 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["relleno", "intenso"],
    images: [],
    colors: ["#5A3E36"],
    isNew: true,
    isBestseller: false
  },
  {
    id: 10,
    name: "Alfajor Triple Chocolate",
    category: "Alfajores",
    price: 110.00,
    rating: 4.6,
    numReviews: 59,
    description: "Alfajor relleno de mousse de chocolate, bañado en cobertura amarga.",
    ingredients: ["Chocolate", "Harina", "Huevos", "Azúcar", "Cacao"],
    allergens: ["Gluten", "Lácteos", "Huevos"],
    calories: "370 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["chocolate", "intenso"],
    images: [],
    colors: ["#3D2C29"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 11,
    name: "Galletas de Limón Glaseadas",
    category: "Galletas",
    price: 55.00,
    rating: 4.4,
    numReviews: 47,
    description: "Galletitas crujientes con un toque cítrico y glaseado de limón.",
    ingredients: ["Harina", "Limón", "Azúcar", "Manteca"],
    allergens: ["Gluten", "Lácteos"],
    calories: "240 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["cítrico", "refrescante"],
    images: [],
    colors: ["#FAFAD2"],
    isNew: true,
    isBestseller: false
  },
  {
    id: 12,
    name: "Tarta de Frutilla",
    category: "Tartas",
    price: 210.00,
    rating: 4.7,
    numReviews: 70,
    description: "Tarta con base sablé, crema pastelera y frutillas frescas.",
    ingredients: ["Harina", "Frutillas", "Crema pastelera", "Manteca"],
    allergens: ["Gluten", "Huevos", "Lácteos"],
    calories: "330 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["fresca", "verano"],
    images: [],
    colors: ["#FF6F91"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 13,
    name: "Torta Oreo",
    category: "Tortas",
    price: 310.00,
    rating: 4.9,
    numReviews: 132,
    description: "Bizcocho de chocolate relleno de crema de Oreo y cobertura crocante.",
    ingredients: ["Galletas Oreo", "Harina", "Huevos", "Queso crema", "Azúcar"],
    allergens: ["Gluten", "Lácteos", "Huevos"],
    calories: "450 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["oreo", "moderna"],
    images: [],
    colors: ["#333333"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 14,
    name: "Empanada de Batata y Canela",
    category: "Empanadas",
    price: 80.00,
    rating: 4.3,
    numReviews: 34,
    description: "Relleno suave de batata especiada, ideal para servir caliente.",
    ingredients: ["Batata", "Canela", "Masa de hojaldre", "Azúcar negra"],
    allergens: ["Gluten"],
    calories: "300 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["dulce", "otoñal"],
    images: [],
    colors: ["#EECFA1"],
    isNew: true,
    isBestseller: false
  },
  {
    id: 15,
    name: "Mini Bites de Brownie y Frambuesa",
    category: "Bites",
    price: 140.00,
    rating: 4.8,
    numReviews: 65,
    description: "Pequeños brownies con centro de frambuesa fresca, perfectos para eventos.",
    ingredients: ["Chocolate", "Frambuesas", "Huevos", "Azúcar"],
    allergens: ["Gluten", "Huevos"],
    calories: "190 kcal por unidad",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["mini", "evento"],
    images: [],
    colors: ["#C71585"],
    isNew: false,
    isBestseller: true
  },
  {
    id: 16,
    name: "Coctail de Mousse en Vasitos",
    category: "Coctail",
    price: 100.00,
    rating: 4.6,
    numReviews: 50,
    description: "Mini vasitos con mousse de chocolate, maracuyá y crema chantilly.",
    ingredients: ["Chocolate", "Maracuyá", "Crema", "Gelatina"],
    allergens: ["Lácteos"],
    calories: "280 kcal por porción",
    image: "https://static.vecteezy.com/system/resources/previews/044/279/881/non_2x/chocolate-chips-on-cookie-on-transparent-background-png.png",
    tags: ["sofisticado", "vasito"],
    images: [],
    colors: ["#FFE4E1"],
    isNew: true,
    isBestseller: true
  }
];